version: "3.3"

services:
        mycontainer:
                image: ubuntu
                stdin_open: true
                tty: true
                volumes:
                        - mivolumen:/workdir

volumes:
        mivolumen:
